import os
import subprocess
import tempfile

def compile_handover_manual(project_id: str) -> bytes:
    """
    Generates a code-based PDF handover manual using Typst.
    It aggregates RFIs, alerts, and field inspections.
    """
    # This is a minimal Typst template. In production, this would be highly complex
    # and populated with data fetched from NeonDB for `project_id`.
    typst_source = f"""
    #set page(paper: "us-letter", margin: 1in)
    #set text(font: "Linux Libertine", size: 12pt)
    
    #align(center)[
      #text(size: 24pt, weight: "bold")[O&M Handover Manual]
      
      #v(1cm)
      Project ID: {project_id}
      
      Generated by: Data Centre EPC Project Intelligence Platform
    ]
    
    #pagebreak()
    
    = 1. Resolved RFIs
    - RFI-001: Structural Requirements for Generator Pads (Resolved)
    - RFI-002: HVAC Cooling Tower Tolerances (Resolved)
    
    = 2. Field Inspections
    - Piping alignment verified. 
    - 1 Defect Corrected (OBS-9999).
    """
    
    with tempfile.TemporaryDirectory() as temp_dir:
        source_file = os.path.join(temp_dir, "handover.typ")
        output_file = os.path.join(temp_dir, "handover.pdf")
        
        with open(source_file, "w") as f:
            f.write(typst_source)
            
        # Compile using typst CLI
        try:
            subprocess.run(["typst", "compile", source_file, output_file], check=True, capture_output=True)
            
            with open(output_file, "rb") as f:
                pdf_bytes = f.read()
                
            return pdf_bytes
        except FileNotFoundError:
            # Fallback if Typst is not installed on the system
            print("Typst CLI not found. Returning raw Typst source code instead.")
            return typst_source.encode('utf-8')
        except subprocess.CalledProcessError as e:
            raise Exception(f"Typst compilation failed: {e.stderr.decode()}")
